### ISSUE TITLE
seaborn freezing

### ISSUE THREAD

**Issue by alvaralmstedt** [parvanehnikpour2024/Parvaneh_course_Project#3]
The script is halting or freezing somewhere after line 105. It is not able to continue after this point even after waiting for 10 minutes.
I will attach an image:

![image](https://github.com/user-attachments/assets/b8f2b695-4876-45c0-a5b7-90f7a7301fc4)

I dont think this is intended but I have asked my colleagues to aslo test in case it is something specific about my machine.

**Comment by parvanehnikpour2024** [comment]
Hi Alvar, I checked this issue and noticed that while running my codes (some where after line 105), I am seeing this message in the terminal: 

**C:\Users\xnikpa\Downloads\Python_project\.venv\Lib\site-packages\umap\umap_.py:1945: UserWarning: n_jobs value 1 
overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism."),** 

However, the remaining codes run with no problem (before and) after this message in my system. I tried to trouble-shoot this and I found that this freezing may be due to how UMAP handles parallelism or memory management on different operating systems. As a probable solution, I tried to avoid setting random_state by removing the **random_state=42** parameter in the UMAP function (line 168). This will allow parallel processing, which might prevent the freezing issue on the Mac. After deleting this parameter (random_state=42, line 168) and re-running the scripts in my Windows system, I had all outputs with no similar message regarding parallelism issue. So I have deleted this in the updated version of my .py file. Hope this edit, will resolve the issue in mac systems.

**Comment by alvaralmstedt** [comment]
Okay yeah I got it to work now. I think the main issue was that it was popping out a plot window wich ended upp behind my terminal so I couldnt see it. It would be nice if you could print some more infromation to the terminal about what is happening rather than just a bunch of data so that the user undestands. Also, please have a look at the other issue with hardcoded inputs.
